export const rankList =[
{ idx: "0", name: '云音乐新歌榜' },
{ idx: "1", name: '云音乐热歌榜' },
{ idx: "2", name: '网易原创歌曲榜' },
{idx:"3",name: '云音乐飙升榜'},
{idx:"4",name: '云音乐电音榜'},
{idx:"5",name: 'UK排行榜周榜'},
{idx:"6",name: '美国Billboard周榜'},
{idx:"7",name: 'KTV唛榜'},
{idx:"8",name: 'iTunes榜'},
{idx:"9",name: 'Hit FM Top榜'},
{idx:"10",name:  '日本Oricon周榜'},
{idx:"11",name:  '韩国Melon排行榜周榜'},
{idx:"12",name:  '韩国Mnet排行榜周榜'},
{idx:"13",name:  '韩国Melon原声周榜'},
{idx:"14",name:  '中国TOP排行榜(港台榜)'},
{idx:"15",name:  '中国新乡村音乐排行榜'},
{idx:"16",name:  '香港电台中文歌曲龙虎榜'},
{idx:"17",name:  '华语金曲榜'},
{idx:"18",name:  '中国嘻哈榜'},
{idx:"19",name:  '法国 NRJ Vos Hits 周榜'},
{idx:"20",name:  '台湾Hito排行榜'},
{idx:"21",name:  'Beatport全球电子舞曲榜'},
{idx:"22",name:  '云音乐ACG音乐榜'},
{idx:"23",name:  '云音乐说唱榜'},
{idx:"24",name: '云音乐古典音乐榜'},
{idx:"25",name: '云音乐国电榜'},
{idx:"26",name: '抖音排行榜'},
{idx:"27",name: '新声榜'},
{idx:"28",name: '云音乐韩语榜'},
{idx:"29",name:  '英国Q杂志中文版周榜'},
{idx:"30",name:  '电竞音乐榜'},
{idx:"31",name:  '云音乐欧美热歌榜'},
{idx:"32",name:  '云音乐欧美新歌榜'},
{idx:"33",name:  '说唱TOP榜'}]